from django.urls import path
from .views import *
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('', home, name='home'),
    path('about/', about,
         name='about'),
    path('servicies/', services, name='servicies'),
    path('contact/', contact, name='contact'),
    path('terms-and-conditions/', T_and_C, name='T&C'),
    path('privacy-policy/', privacy_policy, name="privacy_policy"),
    path('cancellation-refund-policies/', cancellation_refund_policies,
         name='cancellation_refund_policies'),
    path('servicies/internship-program',
         internship_program, name='internship_program'),
    path('servicies/web-development', web_development, name='web_development'),
    path('servicies/software-development', software_development,
         name='software_development'),
    path('servicies/data-analytics', data_analytics, name='data_analytics'),
    path('page-not-found/', error_404_view, name='error_404_view'),
    path('hire_us', hire_us, name='hire_us'),
    path('carriers/jobs', carrier, name='carrier'),

    # Online Tools
    path('tools-library', tools_library, name='tools_library'),
    path("subscribe", subscribe, name='subscribe'),

    # Code & Text Utilities
    path('tools-library/code-and-text-utilities/code-formatter',
         code_formatter, name='code_formatter'),
    path('tools-library/code-and-text-utilities/json-formatter-validator',
         json_formatter_validator, name='json_formatter_validator'),
    path('tools-library/code-and-text-utilities/base64-encoder-decoder',
         base64_encoder_decoder, name='base64_encoder_decoder'),
    path('tools-library/code-and-text-utilities/case-converter',
         case_converter, name='case_converter'),
    path('tools-library/code-and-text-utilities/string-hash-generator',
         string_hash_generator, name='string_hash_generator'),
    path('tools-library/code-and-text-utilities/url-encoder-decoder',
         url_encoder_decoder, name='url_encoder_decoder'),
    path('tools-library/code-and-text-utilities/jwt-decoder-generator',
         jwt_decoder_generator, name='jwt_decoder_generator'),
    path('tools-library/code-and-text-utilities/regex-tester',
         regex_tester, name='regex_tester'),

    # API, Network & Web Analysis Tools
    path('tools-library/api-network-and-web-analysis-tools/api-tester',
         api_tester, name='api_tester'),
    path('tools-library/api-network-and-web-analysis-tools/network-analyzer',
         network_analyzer, name='network_analyzer'),
    path('tools-library/api-network-and-web-analysis-tools/rest-api-tester',
         rest_api_tester, name='rest_api_tester'),
    path('tools-library/api-network-and-web-analysis-tools/http-headers-inspector',
         http_headers_inspector, name='http_headers_inspector'),
    path('tools-library/api-network-and-web-analysis-tools/dns-lookup-tool',
         dns_lookup_tool, name='dns_lookup_tool'),
    path('tools-library/api-network-and-web-analysis-tools/whois-lookup',
         whois_lookup, name='whois_lookup'),
    path('tools-library/api-network-and-web-analysis-tools/ip-address-lookup',
         ip_address_lookup, name='ip_address_lookup'),
    path('tools-library/api-network-and-web-analysis-tools/port-scanner',
         port_scanner, name='port_scanner'),
    path('tools-library/api-network-and-web-analysis-tools/website-screenshot-api',
         website_screenshot_api, name='website_screenshot_api'),
    path('tools-library/api-network-and-web-analysis-tools/download-screenshot',
         download_screenshot, name='download_screenshot'),
    path('tools-library/api-network-and-web-analysis-tools/meta-tag-analyzer',
         meta_tag_analyzer, name='meta_tag_analyzer'),
    path('tools-library/api-network-and-web-analysis-tools/robots-txt-sitemap-validator',
         robots_txt_sitemap_validator, name='robots_txt_sitemap_validator'),
    path('tools-library/api-network-and-web-analysis-tools/ssl-certificate-checker',
         ssl_certificate_checker, name='ssl_certificate_checker'),

    # Security & Authentication Tools
    path('tools-library/security-and-authentication-tools/password-generator',
         password_generator, name='password_generator'),
    path('tools-library/security-and-authentication-tools/password-strength-checker',
         password_strength_checker, name='password_strength_checker'),
    path('tools-library/security-and-authentication-tools/uuid-generator',
         uuid_generator, name='uuid_generator'),
    path('tools-library/security-and-authentication-tools/xss-vulnerability-tester',
         xss_vulnerability_tester, name='xss_vulnerability_tester'),
    path('tools-library/security-and-authentication-tools/sql-injection-tester',
         sql_injection_tester, name='sql_injection_tester'),
    path('tools-library/security-and-authentication-tools/jwt-expiry-checker',
         jwt_expiry_checker, name='jwt_expiry_checker'),

    # Data Conversion & Processing Tools
    path('tools-library/data-conversion-and-processing-tools/csv-to-json-converter',
         csv_to_json_converter, name='csv_to_json_converter'),
    path('tools-library/data-conversion-and-processing-tools/json-to-csv-converter',
         json_to_csv_converter, name='json_to_csv_converter'),
    path('tools-library/data-conversion-and-processing-tools/html-table-to-json-converter',
         html_table_to_json_converter, name='html_table_to_json_converter'),
    path('tools-library/data-conversion-and-processing-tools/html-table-to-csv-converter',
         html_table_to_csv_converter, name='html_table_to_csv_converter'),
    path('tools-library/data-conversion-and-processing-tools/xml-to-json-converter',
         xml_to_json_converter, name='xml_to_json_converter'),
    path('tools-library/data-conversion-and-processing-tools/yaml-to-json-converter',
         yaml_to_json_converter, name='yaml_to_json_converter'),

    # QR Code and Imaging Tools
#     path('tools-library/qr-code-tools/qr-code-generator',
#          qr_code_generator, name='qr_code_generator'),
#     path('tools-library/qr-code-tools/barcode-generator',
#          barcode_generator, name='barcode_generator'),
#     path('tools-library/qr-code-tools/qr-code-scanner',
#          qr_code_scanner, name='qr_code_scanner'),
#     path('tools-library/imaging-tools/exif-data-viewer',
#          exif_data_viewer, name='exif_data_viewer'),
#     path('tools-library/imaging-tools/image-compression-tool',
#          image_compression_tool, name='image_compression_tool'),
#     path('tools-library/imaging-tools/image-format-converter',
#          image_format_converter, name='image_format_converter'),
#     path('tools-library/imaging-tools/color-palette-extractor',
#          color_palette_extractor, name='color_palette_extractor'),
#     path('tools-library/imaging-tools/photo-metadata-remover',
#          photo_metadata_remover, name='photo_metadata_remover'),

    path('crawl/sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]
