from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('about', about,
         name='about'),  # Redirect after login
    path('servicies', services, name='servicies'),
    path('contact', contact, name='contact'),
    path('terms-and-conditions', T_and_C, name='T&C'),
    path('privacy-policy', privacy_policy, name="privacy_policy"),
    path('cancellation-refund-policies', cancellation_refund_policies,
         name='cancellation_refund_policies'),
    path('servicies/internship-program',
         internship_program, name='internship_program'),
    path('servicies/web-development', web_development, name='web_development'),
    path('servicies/software-development', software_development,
         name='software_development'),
    path('servicies/data-analytics', data_analytics, name='data_analytics'),
    path('page-not-found/', error_404_view, name='error_404_view'),
    path('hire_us', hire_us, name='hire_us'),
    path('carriers/jobs', carrier, name='carrier'),

    #Online Tools
    path('tools-library', tools_library, name='tools_library'),
    path("subscribe", subscribe, name='subscribe'),
    path('tools-library/code-formatter', code_formatter, name='code_formatter'),
    path('tools-library/text-diff-checker',
         text_diff_checker, name='text_diff_checker'),
    path('tools-library/json-formatter-validator',
         json_formatter_validator, name='json_formatter_validator'),
    path('tools-library/markdown-to-html-converter',
         markdown_to_html_converter, name='markdown_to_html_converter'),
    path('tools-library/diff-checker', diff_checker, name='diff_checker'),
    path('tools-library/base64-encoder-decoder',
         base64_encoder_decoder, name='base64_encoder_decoder'),
    path('tools-library/case-converter', case_converter, name='case_converter'),
    path('tools-library/string-hash-generator',
         string_hash_generator, name='string_hash_generator'),
    path('tools-library/minifier-beautifier',
         minifier_beautifier, name='minifier_beautifier'),
    path('tools-library/url-encoder-decoder',
         url_encoder_decoder, name='url_encoder_decoder'),
    path('tools-library/jwt-decoder-generator',
         jwt_decoder_generator, name='jwt_decoder_generator'),
    path('tools-library/regex-tester', regex_tester, name='regex_tester'),
    path('tools-library/api-tester', api_tester, name='api_tester'),
    path('tools-library/network-analyzer',
         network_analyzer, name='network_analyzer'),
    path('tools-library/rest-api-tester',
         rest_api_tester, name='rest_api_tester'),
    path('tools-library/http-headers-inspector',
         http_headers_inspector, name='http_headers_inspector'),
    path('tools-library/dns-lookup-tool',
         dns_lookup_tool, name='dns_lookup_tool'),
    path('tools-library/whois-lookup', whois_lookup, name='whois_lookup'),
    path('tools-library/ip-address-lookup',
         ip_address_lookup, name='ip_address_lookup'),
    path('tools-library/port-scanner', port_scanner, name='port_scanner'),
    path('tools-library/website-screenshot-api',
         website_screenshot_api, name='website_screenshot_api'),
    path('tools-library/meta-tag-analyzer',
         meta_tag_analyzer, name='meta_tag_analyzer'),
    path('tools-library/robots-txt-sitemap-validator',
         robots_txt_sitemap_validator, name='robots_txt_sitemap_validator'),
    path('tools-library/ssl-certificate-checker',
         ssl_certificate_checker, name='ssl_certificate_checker'),
]
