# Generated by Django 5.0.7 on 2025-03-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('message', models.TextField()),
                ('reply_sent', models.BooleanField(default=False)),
                ('reply_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HireUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('hiring_details', models.TextField()),
                ('message', models.TextField(blank=True, null=True)),
                ('reply_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
