# Generated by Django 5.0.7 on 2025-03-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
    ]
