# Generated by Django 5.0.7 on 2025-02-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_contactform_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('hiring_details', models.TextField()),
            ],
        ),
    ]
