# Generated by Django 5.0.7 on 2025-03-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_hireus'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireus',
            name='message',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='hireus',
            name='reply_sent',
            field=models.BooleanField(default=False),
        ),
    ]
