# Generated by Django 5.0.7 on 2025-03-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('internship_field', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('issued_at', models.DateField(auto_now_add=True)),
                ('certificate_code', models.CharField(max_length=10)),
                ('certficate', models.FileField(null=True, upload_to='certificates/')),
            ],
        ),
    ]
