from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', admin_login, name='admin_login'),
    path('logout', admin_logout, name='admin_logout'),
    path('forgot-password', forgot_password, name='admin_forgot_password'),
    path('admin_verify-otp', verify_otp, name='admin_verify_otp'),
    path('resend-otp', resend_otp, name='admin_resend_otp'),
    path('reset-password', reset_password, name='admin_reset_password'),
    # Redirect after login
    path('dashboard', admin_dashboard, name='admin_dashboard'),
    path('internship/add-project', add_internship_project,
         name='add_internship_project'),
    path('internship/view-applications', view_internship_applications,
         name='view_internship_applications'),
    path('internship/view-applications/<int:app_id>/approve-reject',
         approve_or_reject_application, name='approve_reject_application'),
    path('internship/project-allocation/<int:app_id>',
         update_project_allocation, name='update_internship_project_allocation'),
    path('internship/received-payments', received_internship_payments,
         name='received_internship_payments'),
    path('internship/process-refund/<str:payment_id>',
         process_refund, name='process_refund'),
    path('internship/eligible-for-offer-letter', eligible_for_internship_offer_letter,
         name='eligible_for_internship_offer_letter'),
    path('internship/view-offer-letter', download_internship_offer_letter,
         name='download_internship_offer_letter'),
    path('internship/send-offer-letter', issue_internship_offer_letter,
         name='issue_internship_offer_letter'),
    path('internship/eligible-for-certificate', eligible_for_internship_certificate,
         name='eligible_for_internship_certificate'),
    path('internship/issue', issue_internship_certificate,
         name='issue_internship_certificate'),
    path("internship/certificate/intern/generate/<str:certificate_code>/",
         generate_internship_certificate, name="generate_internship_certificate"),
    path('internship/eligible-for-certificate',
         eligible_interns_for_certificate, name='eligible_intern_for_certificate'),
    path('internship/upload-certificate', upload_internship_certificate,
         name='internship_certificate_upload'),
    path('internship/issued-certificates', issued_internship_certificates,
         name='issued_internship_certificates'),
    path('contact-us-view', contact_us, name='contact_us_view'),
    path('contact-us-reply/<int:query_id>',
         contact_us_reply, name='contact_us_reply'),
    path('internship/added-projects', added_internship_projects,
         name='added_internship_projects'),
    path('internship/edit-project/<int:project_id>',
         edit_internship_project, name='edit_internship_project'),
    path('internship/delete-project/<int:project_id>',
         delete_internship_project, name='delete_internship_project'),
    path('internship-dashboard', internship_dashboard,
         name='internship_dashboard'),
    path('admin-login-with-otp', admin_login_with_otp,
         name='admin_login_with_otp'),
    path('admin-verify-login-otp', admin_verify_login_otp,
         name='admin_verify_login_otp'),
]