# Generated by Django 5.0.7 on 2024-12-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllottedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='internshipprojects',
            name='duration',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
