# Generated by Django 5.0.7 on 2024-12-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0002_allottedproject_internshipprojects_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipprojects',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
