# Generated by Django 5.0.7 on 2024-12-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='a',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
