# Generated by Django 5.0.7 on 2024-12-15 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_payment_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='a',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
    ]
