# Generated by Django 5.0.7 on 2024-12-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_payment_a_remove_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
