# Generated by Django 5.0.7 on 2024-12-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_payment_refund_amount_payment_refund_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='refund_order_id',
            new_name='refund_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='refund_payment_id',
        ),
    ]
