# Generated by Django 5.0.7 on 2024-12-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_refund_order_id_payment_refund_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='refund_id',
            new_name='refund_payment_id',
        ),
    ]
