# Generated by Django 5.0.7 on 2024-12-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_refund_id_payment_refund_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='refund_signature',
        ),
    ]
