# Generated by Django 5.0.7 on 2024-12-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_payment_refund_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='refund_amount',
        ),
    ]
