# Generated by Django 5.0.7 on 2024-12-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_payment_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='offer_letter',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
