# Generated by Django 5.0.7 on 2024-12-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_internshipapplication_offer_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='offer_letter',
            field=models.BooleanField(default=False),
        ),
    ]
